# Generated by Django 4.1.3 on 2023-04-05 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="question",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="question",
            name="voter",
        ),
        migrations.AddField(
            model_name="question",
            name="voter",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
