# Generated by Django 4.1.3 on 2022-11-08 09:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0002_alter_question_options_question_voter"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("voter", "question_title")},
        ),
    ]
